import babel from "rollup-plugin-babel";
import commonjs from "rollup-plugin-commonjs";
import external from "rollup-plugin-peer-deps-external";
import postcss from "rollup-plugin-postcss";
import resolve from "rollup-plugin-node-resolve";
import url from "rollup-plugin-url";
import svgr from "@svgr/rollup";
import del from "rollup-plugin-delete";

import pkg from "./package.json";

export default {
  // Listing full path for each since the input filename determines the output filename.
  input: [
    "src/Accordion/Accordion",
    "src/AccountNumberMask/AccountNumberMask",
    "src/Alert/Alert",
    "src/BlueBox/BlueBox",
    "src/Button/Button",
    "src/Button/PrintButton",
    "src/ButtonGroup/ButtonGroup",
    "src/Card/Card",
    "src/ClickToExpand/ClickToExpand",
    "src/ColorSwatch/ColorSwatch",
    "src/DataTable/DataTable",
    "src/DataTable/FieldValue",
    "src/DataTable/LinksList",
    "src/DefinitionList/DefinitionList",
    "src/DoNextLinks/DoNextLinks",
    "src/ErrorSummary/ErrorSummary",
    "src/ExpandButton/ExpandButton",
    "src/FAQ/FAQ",
    "src/Form/Form",
    "src/FormInputs/AccountNumberInput/AccountNumberInput",
    "src/FormInputs/Checkbox/Checkbox",
    "src/FormInputs/Checkbox/Checkboxes",
    "src/FormInputs/Combobox/Combobox",
    "src/FormInputs/Combobox/MultiSelectCombobox",
    "src/FormInputs/Combobox/CleanCombobox",
    "src/FormInputs/CurrencyInput/CurrencyInput",
    "src/FormInputs/DateInput/DateInput",
    "src/FormInputs/DatePicker/components/DatePicker",
    "src/FormInputs/DatePicker/components/DateRangePicker",
    "src/FormInputs/DatePicker/components/BankHolidaysContext",
    "src/FormInputs/DatePicker/components/BankHolidaysProvider",
    "src/FormInputs/DropdownButton/DropdownButton",
    "src/FormInputs/InputError/InputError",
    "src/FormInputs/InputHelp/InputHelp",
    "src/FormInputs/Label/Label",
    "src/FormInputs/MaskedTextInput/MaskedTextInput",
    "src/FormInputs/PhoneInput/PhoneInput",
    "src/FormInputs/RadioButton/RadioButton",
    "src/FormInputs/RadioFieldset/RadioFieldset",
    "src/FormInputs/ReadOnlyInput/ReadOnlyInput",
    "src/FormInputs/SelectCountry/SelectCountry",
    "src/FormInputs/SelectInput/SelectInput",
    "src/FormInputs/SelectState/SelectState",
    "src/FormInputs/SelectTypeahead/SelectTypeahead",
    "src/FormInputs/TextInput/TextInput",
    "src/FormInputs/ZipcodeInput/ZipcodeInput",
    "src/FormSection/FormSection",
    "src/Headers/H1/H1",
    "src/Headers/H2/H2",
    "src/Headers/H3/H3",
    "src/Headers/H4/H4",
    "src/Headers/H5/H5",
    "src/Headers/H6/H6",
    "src/Headers/Headline/Headline",
    "src/hooks/useApi/useApi",
    "src/hooks/useForm",
    "src/hooks/useInterval",
    "src/hooks/useIsMobile",
    "src/hooks/useLocalStorage",
    "src/hooks/useSafeState",
    "src/hooks/useToggle",
    "src/hooks/useTrackPageLoad",
    "src/hooks/useWindowSize",
    "src/hooks/forms/useFormHandlers",
    "src/hooks/forms/useFormValidation",
    "src/HR/HR",
    "src/Icons/ArrowLeftIcon",
    "src/Icons/ArrowRightIcon",
    "src/Icons/Calendar7Icon",
    "src/Icons/CalendarCheckIcon",
    "src/Icons/CalendarIcon",
    "src/Icons/ChevronDownIcon",
    "src/Icons/CreditCardIcon",
    "src/Icons/DeleteIcon",
    "src/Icons/EBillIcon",
    "src/Icons/EBillLinkIcon",
    "src/Icons/EBillThinIcon",
    "src/Icons/ElectronicIcon",
    "src/Icons/ErrorIcon",
    "src/Icons/GrayCalendarIcon",
    "src/Icons/InfoIcon",
    "src/Icons/InfoOpenIcon",
    "src/Icons/MailIcon",
    "src/Icons/MinusIcon",
    "src/Icons/MobilePhoneIcon",
    "src/Icons/MoneyMarketIcon",
    "src/Icons/PencilIcon",
    "src/Icons/PlusIcon",
    "src/Icons/PlusIconCircle",
    "src/Icons/PrintIcon",
    "src/Icons/RevolvingIcon",
    "src/Icons/SuccessIcon",
    "src/Icons/WarningIcon",
    "src/IdleTimeout/IdleTimeout",
    "src/LastFourMask/LastFourMask",
    "src/Modal/Modal",
    "src/Modal/ConfirmModal/ConfirmModal",
    "src/ScenarioSelector/ScenarioSelector",
    "src/ScheduledPaymentCard/ScheduledPaymentCard",
    "src/SecondaryNav/SecondaryNav",
    "src/SmartLink/SmartLink",
    "src/Spinner/Spinner",
    "src/SpinnerWrapper/SpinnerWrapper",
    "src/SteppedForm/SteppedForm",
    "src/SubmitButton/SubmitButton",
    "src/Tooltip/Tooltip",
    "src/TouchPhoneNumber/TouchPhoneNumber",
    "src/utils/debounce",
    "src/utils/arrayUtils",
    "src/utils/dateUtils",
    "src/utils/formattingUtils",
    "src/utils/masking",
    "src/utils/mergeDeep",
    "src/utils/propIs",
    "src/utils/tracking",
    "src/utils/urls",
    "src/utils/validators",
  ],
  output: [
    {
      dir: pkg.main,
      format: "cjs",
      sourcemap: true,
      // Allow exporting both default and named exports in same file without throwing a warning. Fine since we're consuming via ES Modules.
      // More info here: https://github.com/rollup/rollup/issues/1961
      exports: "named",
    },
    {
      dir: pkg.module,
      format: "esm",
      sourcemap: true,
    },
  ],
  plugins: [
    del({ targets: ["lib/*", "lib-es/*"] }),
    external(),
    postcss({
      modules: true,
    }),
    url(),
    svgr(),
    babel({
      exclude: "node_modules/**",
    }),
    resolve(),
    commonjs({
      include: "node_modules/**",
      namedExports: {
        //circleCI chokes without specifying
        "node_modules/react-is/index.js": [
          "isForwardRef",
          "isValidElementType",
        ],
        "node_modules/downshift/node_modules/react-is/index.js": [
          "isForwardRef",
        ],
        "node_modules/react-table/index.js": [
          "useTable",
          "useExpanded",
          "usePagination",
          "useFilters",
          "useSortBy",
        ],
      },
    }),
  ],
};
