export const FREQUENCY_TYPE = {
  ONE_TIME: "ONE_TIME",
  REPEATING: "REPEATING",
  ONCE_A_WEEK: "ONCE_A_WEEK",
  ONCE_IN_2_WEEKS: "ONCE_IN_2_WEEKS",
  ONCE_IN_4_WEEKS: "ONCE_IN_4_WEEKS",
  TWICE_A_MONTH: "TWICE_A_MONTH",
  ONCE_A_MONTH: "ONCE_A_MONTH",
  ONCE_IN_2_MONTHS: "ONCE_IN_2_MONTHS",
  ONCE_IN_3_MONTHS: "ONCE_IN_3_MONTHS",
  ONCE_IN_6_MONTHS: "ONCE_IN_6_MONTHS",
  ONCE_A_YEAR: "ONCE_A_YEAR",
  EBILL_AUTOPAY: "EBILL_AUTOPAY",
};
