// This payee data is centralized because it's used by payeeMockData.js and customerEnrollmentStatusMockData.js

const {
  formatDate,
  getNextWeekday,
  isWeekendDay,
} = require("reusable/lib/dateUtils");

const earliestPaymentDate = formatDate(
  isWeekendDay(new Date()) ? getNextWeekday(new Date()) : new Date()
);

const { daysInFuture } = require("./mockDataUtils");

// Each config below is shared by payee and customerEnrollmentStatus mock APIs
// Their scenario config and mock data need to stay in sync to mimic production.
module.exports = [
  {
    id: 1,
    scenario: "4 payees, 2 reminders, 1 unverified, 1 not reminder eligible",
    status: {
      eligible: true,
      fundsAvailable: true,
      enrolledInFIS: true,
      enrolledInDFS: true,
    },
    payees: [
      {
        id: "102260911",
        name: "Wachovia Bank",
        nickName: "Wachovia Bank active ebill",
        accountNumber: "**3C",
        verified: true,
        status: "ACTIVE",
        fundingId: "111",
        earliestPaymentDate,
        leadDays: 2,
        cutOffTime: "13:00:00",
        reminderEligible: true,
        deliveryMethod: "STANDARD_ELECTRONIC",
        ebillStatus: "ACTIVE",
        ebillCycle: "ONCE_A_MONTH",
        reminder: {
          frequency: "ONCE_IN_6_MONTHS",
          amount: 42.51,
          date: "2020-09-12",
        },
        ebill: {
          id: "208237964",
          type: "DIRECT",
          status: "UNPAID",
          paymentURIDetails: "https://bde.money-movement.com",
          cycleStatus: "IN_CYCLE",
          payeeId: "102260911",
          dueDate: "2020-02-25",
          statementDate: "2019-11-04",
          receivedDate: "2019-11-25",
          totalDue: 42.51,
          minimumDue: 22.51,
        },
      },
      {
        id: "102260910",
        name: "Discover Credit Card",
        nickName: "DiscoverCard",
        accountNumber: "************4065",
        address: {
          postalCode: "601976103",
          formatted: "PO BOX 6103  \nCAROL STREAM IL 601976103\n USA",
        },
        verified: true,
        status: "ACTIVE",
        fundingId: "111",
        earliestPaymentDate,
        leadDays: 2,
        cutOffTime: "13:00:00",
        reminderEligible: true,
        deliveryMethod: "STANDARD_ELECTRONIC",
        ebillStatus: "AVAILABLE",
        ebillCycle: "ONCE_A_MONTH",
        reminder: {
          frequency: "ONCE_IN_6_MONTHS",
          amount: 42.51,
          date: "2020-12-14",
        },
        repeatingPayment: {
          memo: "this is a managed payee",
          ruleId: "999SSS",
          frequency: "ONCE_IN_4_WEEKS",
          amount: 22.51,
          nextPaymentDate: daysInFuture(20),
          startDate: "2020-05-19",
          noOfPayments: 20,
        },
      },
      {
        id: "102260912",
        name: "Citibank Checking",
        nickName: "My Checking",
        accountNumber: "*******2374",
        phoneNumber: {
          number: "1234567890",
          formatted: "123-456-7890",
        },
        address: {
          streetAddress: "123 Sesame Street",
          extendedAddress: "",
          locality: "Indianapolis",
          region: "IN",
          postalCode: "46220",
          formatted: "123 Sesame Street  \nIndianapolis IN 462201234\n USA",
        },
        verified: false,
        reminderEligible: true,
        status: "ACTIVE",
        fundingId: "111",
        earliestPaymentDate,
        leadDays: 4,
        cutOffTime: "13:00:00",
        deliveryMethod: "TRUST_CHECK",
        ebillStatus: "NOT_AVAILABLE",
        repeatingPayment: {
          memo: "this is a managed payee",
          ruleId: "123AAA",
          frequency: "ONCE_IN_4_WEEKS",
          amount: 122.05,
          nextPaymentDate: daysInFuture(20),
          noOfPayments: 12,
          startDate: "2020-05-15",
        },
      },
      {
        id: "102260913",
        name: "Not reminder eligible",
        nickName: "Test Payee 4",
        accountNumber: "*******1574",
        phoneNumber: {
          number: "1234567890",
          formatted: "123-456-7890",
        },
        address: {
          streetAddress: "123 Sesame Street",
          extendedAddress: "",
          locality: "Indianapolis",
          region: "IN",
          postalCode: "46220",
          formatted: "123 Sesame Street  \nIndianapolis IN 462201234\n USA",
        },
        verified: false,
        status: "ACTIVE",
        fundingId: "111",
        earliestPaymentDate,
        leadDays: 4,
        cutOffTime: "13:00:00",
        deliveryMethod: "TRUST_CHECK",
        ebillStatus: "PENDING_ACTIVATION",
      },
      {
        id: "102268276",
        name: "Not reminder eligible",
        nickName: "Test Payee 5",
        accountNumber: "*******1575",
        phoneNumber: {
          number: "1234567890",
          formatted: "123-456-7890",
        },
        address: {
          streetAddress: "123 Sesame Street",
          extendedAddress: "",
          locality: "Indianapolis",
          region: "IN",
          postalCode: "46220",
          formatted: "123 Sesame Street  \nIndianapolis IN 462201234\n USA",
        },
        verified: false,
        status: "ACTIVE",
        fundingId: "111",
        earliestPaymentDate,
        leadDays: 4,
        cutOffTime: "13:00:00",
        deliveryMethod: "TRUST_CHECK",
        ebillStatus: "PENDING_ACTIVATION",
      },
      {
        id: "102262917",
        name: "Not reminder eligible",
        nickName: "Test Payee with Only Postal Code in address",
        accountNumber: "*******1576",
        phoneNumber: {
          number: "1234567890",
          formatted: "123-456-7890",
        },
        address: {
          postalCode: "46220",
        },
        verified: true,
        status: "ACTIVE",
        fundingId: "111",
        earliestPaymentDate,
        leadDays: 4,
        cutOffTime: "13:00:00",
        deliveryMethod: "TRUST_CHECK",
        ebillStatus: "PENDING_ACTIVATION",
      },
      {
        id: "102281723",
        name: "Discover Credit Card",
        nickName: "Discover CC available ebill",
        accountNumber: "*******1576",
        verified: true,
        status: "ACTIVE",
        fundingId: "111",
        deliveryMethod: "STANDARD_ELECTRONIC",
        earliestPaymentDate,
        leadDays: 4,
        cutOffTime: "13:00:00",
        reminderEligible: true,
        cardPaymentInfo: {
          dueDate: "2020-09-14",
          minimumBalance: 0.0,
          statementBalance: 20000.7,
          currentBalance: 1960.7,
        },
        ebillStatus: "AVAILABLE",
      },
      {
        id: "102260999",
        name: "Chase Bank",
        nickName: "Chase Bank has Autopay",
        accountNumber: "*******9999",
        verified: true,
        status: "ACTIVE",
        fundingId: "111",
        earliestPaymentDate,
        leadDays: 2,
        cutOffTime: "13:00:00",
        reminderEligible: true,
        deliveryMethod: "STANDARD_ELECTRONIC",
        ebillStatus: "ACTIVE",
        ebillCycle: "ONCE_A_MONTH",
        reminder: {
          frequency: "ONCE_IN_6_MONTHS",
          amount: 42.51,
          date: "2020-09-12",
        },
        automaticPayment: {
          amount: "PAY_FULL_BALANCE",
          paymentDate: "ON_DUE_DATE",
        },
        ebill: {
          id: "208237969",
          type: "DIRECT",
          status: "UNPAID",
          paymentURIDetails: "https://bde.money-movement.com",
          cycleStatus: "IN_CYCLE",
          payeeId: "102260999",
          dueDate: "2019-12-30",
          statementDate: "2019-11-04",
          receivedDate: "2019-11-25",
          totalDue: 42.51,
          minimumDue: 22.51,
        },
      },
      {
        id: "102260919",
        name: "Happy Bank",
        nickName: "Happy Bank Ebills Repeating Payment",
        accountNumber: "*******9998",
        verified: true,
        status: "ACTIVE",
        fundingId: "111",
        earliestPaymentDate,
        leadDays: 2,
        cutOffTime: "13:00:00",
        reminderEligible: true,
        deliveryMethod: "STANDARD_ELECTRONIC",
        ebillStatus: "ACTIVE",
        ebillCycle: "ONCE_A_MONTH",
        reminder: {
          frequency: "ONCE_IN_6_MONTHS",
          amount: 42.51,
          date: "2020-09-12",
        },
        repeatingPayment: {
          memo: "ebills repeating",
          ruleId: "333ZZZ",
          frequency: "ONCE_IN_4_WEEKS",
          amount: 235.05,
          nextPaymentDate: daysInFuture(20),
          noOfPayments: 12,
          startDate: "2020-05-15",
        },
        ebill: {
          id: "208237969",
          type: "DIRECT",
          status: "UNPAID",
          paymentURIDetails: "https://bde.money-movement.com",
          cycleStatus: "IN_CYCLE",
          payeeId: "102260998",
          dueDate: "2019-12-30",
          statementDate: "2019-11-04",
          receivedDate: "2019-11-25",
          totalDue: 235.05,
          minimumDue: 22.51,
        },
      },
      {
        id: "102260666",
        name: "Vampire Bank",
        nickName: "Vampire Bank ebill enrolled but no ebill yet",
        accountNumber: "**66",
        verified: true,
        status: "ACTIVE",
        fundingId: "111",
        earliestPaymentDate,
        leadDays: 2,
        cutOffTime: "13:00:00",
        reminderEligible: true,
        deliveryMethod: "STANDARD_ELECTRONIC",
        ebillStatus: "ACTIVE",
        ebillCycle: "ONCE_A_MONTH",
        reminder: {
          frequency: "ONCE_IN_6_MONTHS",
          amount: 42.51,
          date: "2020-09-12",
        },
      },
      {
        id: "102260111",
        name: "Covid has Repeating Nothing Scheduled",
        nickName: "Covid has Repeating Nothing Scheduled",
        accountNumber: "*******7788",
        verified: false,
        status: "ACTIVE",
        fundingId: "111",
        earliestPaymentDate,
        leadDays: 2,
        cutOffTime: "13:00:00",
        reminderEligible: true,
        deliveryMethod: "TRUST_CHECK",
        ebillStatus: "NOT_AVAILABLE",
        address: {
          streetAddress: "123 Sesame Street",
          extendedAddress: "2nd Floor",
          locality: "Indianapolis",
          region: "IN",
          postalCode: "462201234",
          formatted: "123 Sesame Street  \nIndianapolis IN 462201234\n USA",
        },
        repeatingPayment: {
          memo: "i has the covid",
          ruleId: "777888",
          frequency: "ONCE_IN_4_WEEKS",
          amount: 235.05,
          nextPaymentDate: daysInFuture(20),
          startDate: "2020-05-15",
        },
      },
      {
        id: "102260148",
        name: "Ending Repeating Payment",
        nickName: "Ending Repeating Payment",
        accountNumber: "*******7788",
        verified: false,
        status: "ACTIVE",
        fundingId: "111",
        earliestPaymentDate,
        leadDays: 2,
        cutOffTime: "13:00:00",
        reminderEligible: true,
        deliveryMethod: "TRUST_CHECK",
        ebillStatus: "NOT_AVAILABLE",
        address: {
          streetAddress: "123 Sesame Street",
          extendedAddress: "2nd Floor",
          locality: "Indianapolis",
          region: "IN",
          postalCode: "462201234",
          formatted: "123 Sesame Street  \nIndianapolis IN 462201234\n USA",
        },
        repeatingPayment: {
          //this payment is ending, all payments have already been scheduled so the nextPaymentDate doesn't get returned
          memo: "I will end soon",
          ruleId: "111222",
          frequency: "ONCE_IN_4_WEEKS",
          amount: 990.0,
          startDate: "2020-05-15",
          noOfPayments: "2",
        },
      },
    ],
  },
  {
    id: 2,
    scenario: "1 payee, 0 reminders, not reminder eligible",
    status: {
      eligible: true,
      fundsAvailable: true,
      enrolledInFIS: true,
      enrolledInDFS: true,
    },
    payees: [
      {
        id: "102260914",
        name: "SOAPtest00",
        nickName: "Test Payee 00",
        accountNumber: null,
        phoneNumber: {
          number: "1234567890",
          formatted: "123-456-7890",
        },
        address: {
          streetAddress: "123 Sesame Street",
          extendedAddress: "2nd Floor",
          locality: "Indianapolis",
          region: "IN",
          postalCode: "462201234",
          formatted: "123 Sesame Street  \nIndianapolis IN 462201234\n USA",
        },
        verified: false,
        status: "ACTIVE",
        fundingId: "111",
        earliestPaymentDate,
        leadDays: 4,
        cutOffTime: "13:00:00",
        deliveryMethod: "TRUST_CHECK",
        ebillStatus: "NOT_AVAILABLE",
      },
    ],
  },
  {
    id: 3,
    scenario: "No Payees",
    status: {
      eligible: true,
      fundsAvailable: true,
      enrolledInFIS: true,
      enrolledInDFS: true,
    },
    payees: [],
  },
  {
    id: 4,
    scenario: "1 payee, 1 reminder",
    status: {
      eligible: true,
      fundsAvailable: true,
      enrolledInFIS: true,
      enrolledInDFS: true,
    },
    payees: [
      {
        id: "102260910",
        name: "Discover Credit Card",
        nickName: "Discover Credit 4065",
        accountNumber: "************4065",
        address: {
          postalCode: "601976103",
          formatted: "PO BOX 6103  \nCAROL STREAM IL 601976103\n USA",
        },
        verified: true,
        status: "ACTIVE",
        fundingId: "111",
        earliestPaymentDate,
        leadDays: 2,
        cutOffTime: "13:00:00",
        reminderEligible: true,
        deliveryMethod: "STANDARD_ELECTRONIC",
        ebillStatus: "AVAILABLE",
        ebillCycle: "ONCE_A_MONTH",
        reminder: {
          frequency: "ONCE_IN_6_MONTHS",
          amount: 42.51,
          date: "2020-12-14",
        },
        repeatingPayment: {
          memo: "this is a managed payee",
          ruleId: "999SSS",
          frequency: "ONCE_IN_4_WEEKS",
          amount: 22.51,
          nextPaymentDate: daysInFuture(20),
          noOfPayments: 20,
        },
      },
    ],
  },
  {
    id: 5,
    scenario: "Unenrolled: Not eligible",
    status: {
      eligible: false,
      fundsAvailable: false,
      enrolledInFIS: false,
      enrolledInDFS: false,
    },
    payees: [],
  },
  {
    id: 6,
    scenario: "Unenrolled: Eligible - No Funds Available",
    status: {
      eligible: true,
      fundsAvailable: false,
      enrolledInFIS: false,
      enrolledInDFS: false,
    },
    payees: [],
  },
  {
    id: 7,
    scenario: "Unenrolled: Eligible - Brand New Customer (BAU)",
    status: {
      eligible: true,
      fundsAvailable: true,
      enrolledInFIS: false,
      enrolledInDFS: false,
    },
    payees: [],
  },
  {
    id: 8,
    scenario: "Unenrolled: Eligible - Migrate Customer from FIS",
    status: {
      eligible: true,
      fundsAvailable: true,
      enrolledInFIS: true,
      enrolledInDFS: false,
    },
    payees: [],
  },
  {
    id: 9,
    scenario: "Enrolled: 10 payees, 10 eligible ebill payees",
    status: {
      eligible: true,
      fundsAvailable: true,
      enrolledInFIS: true,
      enrolledInDFS: true,
    },
    payees: [
      {
        id: "102260910",
        name: "Discover Credit Cards",
        nickName: "DiscoverCard",
        accountNumber: "************4065",
        address: {
          postalCode: "601976103",
          formatted: "PO BOX 6103  \nCAROL STREAM IL 601976103\n USA",
        },
        verified: true,
        status: "ACTIVE",
        fundingId: "111",
        earliestPaymentDate,
        leadDays: 2,
        cutOffTime: "13:00:00",
        reminderEligible: true,
        deliveryMethod: "STANDARD_ELECTRONIC",
        ebillStatus: "AVAILABLE",
        ebillCycle: "ONCE_A_MONTH",
        reminder: {
          frequency: "ONCE_IN_6_MONTHS",
          amount: 42.51,
          date: "2020-12-14",
        },
        repeatingPayment: {
          memo: "this is a managed payee",
          ruleId: "999SSS",
          frequency: "ONCE_IN_4_WEEKS",
          amount: 22.51,
          nextPaymentDate: daysInFuture(20),
          startDate: "2019-09-15",
          noOfPayments: 20,
        },
      },
      {
        id: "102278421",
        name: "Cox Communications",
        nickName: "cox com",
        accountNumber: "************7980",
        address: {
          postalCode: "601976103",
          formatted: "PO BOX 6103  \nCAROL STREAM IL 601976103\n USA",
        },
        verified: true,
        status: "ACTIVE",
        fundingId: "111",
        earliestPaymentDate,
        leadDays: 2,
        cutOffTime: "13:00:00",
        reminderEligible: true,
        deliveryMethod: "STANDARD_ELECTRONIC",
        ebillStatus: "AVAILABLE",
        ebillCycle: "ONCE_A_MONTH",
        reminder: {
          frequency: "ONCE_IN_6_MONTHS",
          amount: 42.51,
          date: "2020-12-14",
        },
        repeatingPayment: {
          memo: "this is a managed payee",
          ruleId: "999SSS",
          frequency: "ONCE_IN_4_WEEKS",
          amount: 22.51,
          nextPaymentDate: daysInFuture(20),
          startDate: "2019-09-15",
          noOfPayments: 20,
        },
      },
      {
        id: "102278437",
        name: "Mid Continent Communications",
        nickName: "mid com",
        accountNumber: "*****7898",
        verified: true,
        status: "ACTIVE",
        fundingId: "111",
        earliestPaymentDate,
        leadDays: 2,
        cutOffTime: "13:00:00",
        reminderEligible: true,
        deliveryMethod: "STANDARD_ELECTRONIC",
        ebillStatus: "AVAILABLE",
        ebillCycle: "ONCE_A_MONTH",
        reminder: {
          frequency: "ONCE_IN_6_MONTHS",
          amount: 42.51,
          date: "2020-09-12",
        },
        billInfo: {
          billId: "431253619",
          minimumDue: 22.51,
          totalDue: 42.51,
          status: "UNPAID",
          url: "https://bde.money-movement.com",
          statementDate: "2019-11-04",
          dueDate: "2019-11-25",
          cycleStatus: "IN_CYCLE",
        },
      },
      {
        id: "102278440",
        name: "Verizon Wireless",
        nickName: "Verizon Wireless",
        accountNumber: "******7898",
        phoneNumber: {
          number: "1234567890",
          formatted: "123-456-7890",
        },
        address: {
          streetAddress: "123 Sesame Street",
          extendedAddress: "",
          locality: "Indianapolis",
          region: "IN",
          postalCode: "46220",
          formatted: "123 Sesame Street  \nIndianapolis IN 462201234\n USA",
        },
        verified: false,
        reminderEligible: true,
        status: "ACTIVE",
        fundingId: "111",
        earliestPaymentDate,
        leadDays: 4,
        cutOffTime: "13:00:00",
        deliveryMethod: "TRUST_CHECK",
        ebillStatus: "AVAILABLE",
        repeatingPayment: {
          memo: "this is a managed payee",
          ruleId: "123AAA",
          frequency: "ONCE_IN_4_WEEKS",
          amount: 122.05,
          nextPaymentDate: daysInFuture(20),
          startDate: "2019-09-15",
        },
      },
      {
        id: "102278397",
        name: "Nissan Motor Acceptance",
        nickName: "Nissan Motor Acceptance",
        accountNumber: "*************0001",
        phoneNumber: {
          number: "1234567890",
          formatted: "123-456-7890",
        },
        address: {
          streetAddress: "123 Sesame Street",
          extendedAddress: "",
          locality: "Indianapolis",
          region: "IN",
          postalCode: "46220",
          formatted: "123 Sesame Street  \nIndianapolis IN 462201234\n USA",
        },
        verified: false,
        status: "ACTIVE",
        fundingId: "111",
        earliestPaymentDate,
        leadDays: 4,
        cutOffTime: "13:00:00",
        deliveryMethod: "TRUST_CHECK",
        ebillStatus: "AVAILABLE",
      },
      {
        id: "102278398",
        name: "Salem Five Bank",
        nickName: "Salem Five Bank",
        accountNumber: "************0001",
        phoneNumber: {
          number: "1234567890",
          formatted: "123-456-7890",
        },
        address: {
          streetAddress: "123 Sesame Street",
          extendedAddress: "",
          locality: "Indianapolis",
          region: "IN",
          postalCode: "46220",
          formatted: "123 Sesame Street  \nIndianapolis IN 462201234\n USA",
        },
        verified: false,
        status: "ACTIVE",
        fundingId: "111",
        earliestPaymentDate,
        leadDays: 4,
        cutOffTime: "13:00:00",
        deliveryMethod: "TRUST_CHECK",
        ebillStatus: "AVAILABLE",
      },
      {
        id: "102278443",
        name: "Wells Fargo Home Mortgage",
        nickName: "Wells Fargo Home Mortgage",
        accountNumber: "******4789",
        phoneNumber: {
          number: "1234567890",
          formatted: "123-456-7890",
        },
        address: {
          streetAddress: "123 Sesame Street",
          extendedAddress: "",
          locality: "Indianapolis",
          region: "IN",
          postalCode: "46220",
          formatted: "123 Sesame Street  \nIndianapolis IN 462201234\n USA",
        },
        verified: false,
        status: "ACTIVE",
        fundingId: "111",
        earliestPaymentDate,
        leadDays: 4,
        cutOffTime: "13:00:00",
        deliveryMethod: "TRUST_CHECK",
        ebillStatus: "AVAILABLE",
      },
      {
        id: "102278422",
        name: "Citi Cards",
        nickName: "Citi Cards",
        accountNumber: "******3333",
        phoneNumber: {
          number: "1234567890",
          formatted: "123-456-7890",
        },
        address: {
          streetAddress: "123 Sesame Street",
          extendedAddress: "",
          locality: "Indianapolis",
          region: "IN",
          postalCode: "46220",
          formatted: "123 Sesame Street  \nIndianapolis IN 462201234\n USA",
        },
        verified: false,
        status: "ACTIVE",
        fundingId: "111",
        earliestPaymentDate,
        leadDays: 4,
        cutOffTime: "13:00:00",
        deliveryMethod: "TRUST_CHECK",
        ebillStatus: "AVAILABLE",
      },
      {
        id: "289911313",
        name: "Burlington Credit Card",
        nickName: "Burlington Credit Card",
        accountNumber: "******2160",
        phoneNumber: {
          number: "1234567890",
          formatted: "123-456-7890",
        },
        address: {
          streetAddress: "123 Sesame Street",
          extendedAddress: "",
          locality: "Indianapolis",
          region: "IN",
          postalCode: "46220",
          formatted: "123 Sesame Street  \nIndianapolis IN 462201234\n USA",
        },
        verified: false,
        status: "ACTIVE",
        fundingId: "111",
        earliestPaymentDate,
        leadDays: 4,
        cutOffTime: "13:00:00",
        deliveryMethod: "TRUST_CHECK",
        ebillStatus: "AVAILABLE",
      },
      {
        id: "290903392",
        name: "Citibank Credit Cards",
        nickName: "Citibank Credit Cards",
        accountNumber: "******5516",
        phoneNumber: {
          number: "1234567890",
          formatted: "123-456-7890",
        },
        address: {
          streetAddress: "123 Sesame Street",
          extendedAddress: "",
          locality: "Indianapolis",
          region: "IN",
          postalCode: "46220",
          formatted: "123 Sesame Street  \nIndianapolis IN 462201234\n USA",
        },
        verified: false,
        status: "ACTIVE",
        fundingId: "111",
        earliestPaymentDate,
        leadDays: 4,
        cutOffTime: "13:00:00",
        deliveryMethod: "TRUST_CHECK",
        ebillStatus: "AVAILABLE",
      },
    ],
  },
  {
    id: 10,
    scenario: "4 payees, 1 eligible ebill payee",
    status: {
      eligible: true,
      fundsAvailable: true,
      enrolledInFIS: true,
      enrolledInDFS: true,
    },
    payees: [
      {
        id: "102260910",
        name: "Discover Credit Cards",
        nickName: "DiscoverCard",
        accountNumber: "************4065",
        address: {
          postalCode: "601976103",
          formatted: "PO BOX 6103  \nCAROL STREAM IL 601976103\n USA",
        },
        verified: true,
        status: "ACTIVE",
        fundingId: "111",
        earliestPaymentDate,
        leadDays: 2,
        cutOffTime: "13:00:00",
        reminderEligible: true,
        deliveryMethod: "STANDARD_ELECTRONIC",
        ebillStatus: "AVAILABLE",
        ebillCycle: "ONCE_A_MONTH",
        reminder: {
          frequency: "ONCE_IN_6_MONTHS",
          amount: 42.51,
          date: "2020-12-14",
        },
        repeatingPayment: {
          memo: "this is a managed payee",
          ruleId: "999SSS",
          frequency: "ONCE_IN_4_WEEKS",
          amount: 22.51,
          nextPaymentDate: daysInFuture(20),
          startDate: "2019-09-15",
          noOfPayments: 20,
        },
      },
      {
        id: "102260911",
        name: "Wachovia Bank",
        nickName: "Wachovia Bank",
        accountNumber: "**3C",
        verified: true,
        status: "ACTIVE",
        fundingId: "111",
        earliestPaymentDate,
        leadDays: 2,
        cutOffTime: "13:00:00",
        reminderEligible: true,
        deliveryMethod: "STANDARD_ELECTRONIC",
        ebillStatus: "ACTIVE",
        ebillCycle: "ONCE_A_MONTH",
        reminder: {
          frequency: "ONCE_IN_6_MONTHS",
          amount: 42.51,
          date: "2020-09-12",
        },
        billInfo: {
          billId: "431253619",
          minimumDue: 22.51,
          totalDue: 42.51,
          status: "UNPAID",
          url: "https://bde.money-movement.com",
          statementDate: "2019-11-04",
          dueDate: "2019-11-25",
          cycleStatus: "IN_CYCLE",
        },
      },
      {
        id: "102260912",
        name: "Citibank Checking",
        nickName: "My Checking",
        accountNumber: "*******2374",
        phoneNumber: {
          number: "1234567890",
          formatted: "123-456-7890",
        },
        address: {
          streetAddress: "123 Sesame Street",
          extendedAddress: "",
          locality: "Indianapolis",
          region: "IN",
          postalCode: "46220",
          formatted: "123 Sesame Street  \nIndianapolis IN 462201234\n USA",
        },
        verified: false,
        reminderEligible: true,
        status: "ACTIVE",
        fundingId: "111",
        earliestPaymentDate,
        leadDays: 4,
        cutOffTime: "13:00:00",
        deliveryMethod: "TRUST_CHECK",
        ebillStatus: "NOT_AVAILABLE",
        repeatingPayment: {
          memo: "this is a managed payee",
          ruleId: "123AAA",
          frequency: "ONCE_IN_4_WEEKS",
          amount: 122.05,
          nextPaymentDate: daysInFuture(20),
          startDate: "2019-09-15",
        },
      },
      {
        id: "102260913",
        name: "Not reminder eligible",
        nickName: "Test Payee 4",
        accountNumber: "*******2374",
        phoneNumber: {
          number: "1234567890",
          formatted: "123-456-7890",
        },
        address: {
          streetAddress: "123 Sesame Street",
          extendedAddress: "",
          locality: "Indianapolis",
          region: "IN",
          postalCode: "46220",
          formatted: "123 Sesame Street  \nIndianapolis IN 462201234\n USA",
        },
        verified: false,
        status: "ACTIVE",
        fundingId: "111",
        earliestPaymentDate,
        leadDays: 4,
        cutOffTime: "13:00:00",
        deliveryMethod: "TRUST_CHECK",
        ebillStatus: "PENDING_ACTIVATION",
      },
    ],
  },
  {
    id: 11,
    scenario: "OOB error (Basic login)",
    status: {},
    payees: [],
  },
  {
    id: 12,
    scenario: "OOB error (Basic oob-bank)",
    status: {},
    payees: [],
  },
];
