const { daysInFuture } = require("./mockDataUtils");

module.exports = {
  default: [
    {
      paymentId: "876060900",
      payee: {
        id: "102260912",
        name: "Citibank Checking",
        nickName: "My Checking",
      },
      paymentMethod: {
        id: "SM1326173",
        accountName: "RETAIL PERSONAL CHECKING",
        accountNumber: "9815",
        preferred: false,
      },
      amount: 122.05,
      deliverByDate: daysInFuture(0),
      memo: "this is a managed payee",
      paymentAddress: {
        streetAddress: "4840 Wright Terr",
        extendedAddress: "APT 111",
        locality: "Skokie",
        region: "IL",
        postalCode: "60077",
      },
      type: "REPEATING",
      ruleId: "123AAA",
      status: "SCHEDULED",
      scheduledOn: daysInFuture(0),
      confirmationNumber: "MB2BGZZ4",
      deliveryMethod: "TRUST_CHECK",
    },
    {
      paymentId: "876060923",
      payee: {
        id: "102260912",
        name: "Citibank Checking",
        nickName: "My Checking",
      },
      paymentMethod: {
        id: "SM1326173",
        accountName: "RETAIL PERSONAL CHECKING",
        accountNumber: "9815",
        preferred: false,
      },
      amount: 100.0,
      deliverByDate: daysInFuture(0),
      memo: "this is a managed payee",
      paymentAddress: {
        streetAddress: "4840 Wright Terr",
        extendedAddress: "APT 111",
        locality: "Skokie",
        region: "IL",
        postalCode: "60077",
      },
      type: "REPEATING",
      ruleId: "123AAA",
      status: "PROCESSING",
      scheduledOn: daysInFuture(0),
      confirmationNumber: "MB2BGZZ4",
      deliveryMethod: "TRUST_CHECK",
    },
    {
      paymentId: "876060909",
      payee: {
        id: "102260148",
        name: "Ending Repeating Payment",
        nickName: "Ending Repeating Payment",
      },
      paymentMethod: {
        id: "SM1326173",
        accountName: "RETAIL PERSONAL CHECKING",
        accountNumber: "9815",
        preferred: false,
      },
      amount: 990.0,
      deliverByDate: daysInFuture(0),
      memo: "I will end soon",
      paymentAddress: {
        streetAddress: "123 Sesame Street",
        extendedAddress: "2nd Floor",
        locality: "Indianapolis",
        region: "IN",
        postalCode: "462201234",
        formatted: "123 Sesame Street  \nIndianapolis IN 462201234\n USA",
      },
      type: "REPEATING",
      ruleId: "111222",
      status: "SCHEDULED",
      scheduledOn: daysInFuture(0),
      confirmationNumber: "MB2BGZZ4",
      deliveryMethod: "TRUST_CHECK",
    },
    {
      paymentId: "876053165",
      payee: {
        id: "102260912",
        name: "Citibank Checking",
        nickName: "My Checking",
      },
      paymentMethod: {
        id: "SM1326173",
        accountName: "RETAIL PERSONAL CHECKING ",
        accountNumber: "9815",
        preferred: false,
      },
      amount: 1.11,
      deliverByDate: "2020-03-26",
      memo: "add one time payment",
      paymentAddress: {
        streetAddress: "4840 Wright Terr",
        locality: "Skokie",
        region: "IL",
        postalCode: "60077",
      },
      type: "ONE_TIME",
      status: "CANCELED",
      scheduledOn: "2019-03-09",
      confirmationNumber: "ZB7B2ZZ4",
      deliveryMethod: "TRUST_CHECK",
    },
    {
      paymentId: "876060831",
      payee: {
        id: "102260912",
        name: "Citibank Checking",
        nickName: "My Checking",
      },
      paymentMethod: {
        id: "SM1326173",
        accountName: "RETAIL PERSONAL CHECKING ",
        accountNumber: "9815",
        preferred: false,
      },
      amount: 2.05,
      deliverByDate: daysInFuture(10),
      memo: "this is a managed payee",
      paymentAddress: {
        streetAddress: "4840 Wright Terr",
        locality: "Skokie",
        region: "IL",
        postalCode: "60077",
      },
      type: "REPEATING",
      ruleId: "222333",
      status: "FAILED",
      scheduledOn: "2019-09-27",
      confirmationNumber: "9B1BGZZ4",
      deliveryMethod: "TRUST_CHECK",
    },
    {
      paymentId: "876055610",
      payee: {
        id: "102260912",
        name: "Citibank Checking",
        nickName: "My Checking",
      },
      paymentMethod: {
        id: "SM1326173",
        accountName: "RETAIL PERSONAL CHECKING ",
        accountNumber: "9815",
        preferred: false,
      },
      amount: 2.05,
      deliverByDate: "2020-02-25",
      memo: "this is a managed payee",
      paymentAddress: {
        streetAddress: "4840 Wright Terr",
        locality: "Skokie",
        region: "IL",
        postalCode: "60077",
      },
      type: "REPEATING",
      ruleId: "123BBB",
      status: "CANCELED",
      scheduledOn: "2019-09-12",
      confirmationNumber: "IBZB3ZZ4",
      deliveryMethod: "TRUST_CHECK",
    },
    {
      paymentId: "876061028",
      payee: {
        id: "102260910",
        name: "Discover Credit Cards",
        nickName: "DiscoverCard",
        accountNumber: "************4065",
      },
      paymentMethod: {
        id: "SM1326173",
        accountName: "RETAIL PERSONAL CHECKING ",
        accountNumber: "9815",
        preferred: false,
      },
      amount: 2.61,
      deliverByDate: daysInFuture(0),
      memo: "this is one-time",
      note: "notes",
      type: "ONE_TIME",
      status: "FUNDS_CLEARED",
      scheduledOn: "2020-01-07",
      confirmationNumber: "OBEBGZZ4",
      deliveryMethod: "STANDARD_ELECTRONIC",
    },
    {
      paymentId: "876059964",
      payee: {
        id: "102260912",
        name: "Citibank Checking",
        nickName: "My Checking",
      },
      paymentMethod: {
        id: "SM1326173",
        accountName: "RETAIL PERSONAL CHECKING ",
        accountNumber: "9815",
        preferred: false,
      },
      amount: 2.5,
      deliverByDate: "2020-01-23",
      memo: "this is one-time",
      paymentAddress: {
        streetAddress: "4840 Wright Terr",
        locality: "Skokie",
        region: "IL",
        postalCode: "60077",
      },
      type: "REPEATING",
      ruleId: "123CCC",
      status: "CANCELED",
      scheduledOn: "2019-09-24",
      confirmationNumber: "JB5B5ZZ4",
      deliveryMethod: "TRUST_CHECK",
    },
    {
      paymentId: "876061029",
      payee: {
        id: "102260910",
        name: "Discover Credit Cards",
        nickName: "DiscoverCard",
        accountNumber: "************4065",
      },
      paymentMethod: {
        id: "SM1326173",
        accountName: "RETAIL PERSONAL CHECKING ",
        accountNumber: "*****9815",
        preferred: false,
      },
      amount: 22.51,
      deliverByDate: "2020-01-07",
      note: "notes",
      type: "ONE_TIME",
      ruleId: "999SSS",
      status: "COMPLETED",
      scheduledOn: "2019-09-27",
      confirmationNumber: "OBEBGZZ4",
      deliveryMethod: "STANDARD_ELECTRONIC",
    },
    {
      paymentId: "876061029",
      payee: {
        id: "102260910",
        name: "Discover Credit Cards",
        nickName: "DiscoverCard",
        accountNumber: "************4065",
      },
      paymentMethod: {
        id: "SM1326173",
        accountName: "RETAIL PERSONAL CHECKING ",
        accountNumber: "*****9815",
        preferred: false,
      },
      amount: 22.51,
      deliverByDate: "2020-02-07",
      note: "notes",
      type: "REPEATING",
      ruleId: "999SSS",
      status: "COMPLETED",
      scheduledOn: "2019-09-27",
      confirmationNumber: "OBEBGZZ4",
      deliveryMethod: "STANDARD_ELECTRONIC",
    },
    {
      paymentId: "876061027",
      payee: {
        id: "102260910",
        name: "Discover Credit Cards",
        nickName: "DiscoverCard",
        accountNumber: "************4065",
      },
      paymentMethod: {
        id: "SM1326173",
        accountName: "RETAIL PERSONAL CHECKING",
        accountNumber: "******9815",
        preferred: false,
      },
      amount: 22.51,
      deliverByDate: daysInFuture(0),
      type: "REPEATING",
      ruleId: "123AAB",
      status: "COMPLETED",
      scheduledOn: "2020-09-27",
      confirmationNumber: "VBEBGZZ4",
      deliveryMethod: "STANDARD_ELECTRONIC",
    },
    {
      paymentId: "876059398",
      payee: {
        id: "102260912",
        name: "Citibank Checking",
        nickName: "My Checking",
      },
      paymentMethod: {
        id: "SM1326173",
        accountName: "RETAIL PERSONAL CHECKING ",
        accountNumber: "9815",
        preferred: false,
      },
      amount: 122.05,
      deliverByDate: daysInFuture(10),
      memo: "cat club dues",
      note: "notes",
      paymentAddress: {
        streetAddress: "4840 Wright Terr",
        locality: "Skokie",
        region: "IL",
        postalCode: "60077",
      },
      type: "REPEATING",
      ruleId: "123AAA",
      status: "COMPLETED",
      scheduledOn: "2019-09-23",
      confirmationNumber: "PBOBFZZ4",
      deliveryMethod: "TRUST_CHECK",
    },
    {
      paymentId: "876059300",
      payee: {
        id: "102260912",
        name: "Citibank Checking",
        nickName: "My Checking",
      },
      paymentMethod: {
        id: "SM1326173",
        accountName: "RETAIL PERSONAL CHECKING ",
        accountNumber: "9815",
        preferred: false,
      },
      amount: 122.05,
      deliverByDate: daysInFuture(30),
      memo: "cat club dues",
      note: "notes",
      paymentAddress: {
        streetAddress: "4840 Wright Terr",
        locality: "Skokie",
        region: "IL",
        postalCode: "60077",
      },
      type: "REPEATING",
      ruleId: "123AAA",
      status: "COMPLETED",
      scheduledOn: "2019-09-23",
      confirmationNumber: "PBOBFZZ4",
      deliveryMethod: "TRUST_CHECK",
    },
    {
      paymentId: "876059301",
      payee: {
        id: "102260912",
        name: "Citibank Checking",
        nickName: "My Checking",
      },
      paymentMethod: {
        id: "SM1326173",
        accountName: "RETAIL PERSONAL CHECKING ",
        accountNumber: "9815",
        preferred: false,
      },
      amount: 122.05,
      deliverByDate: "2020-11-22",
      memo: "cat club dues",
      note: "notes",
      paymentAddress: {
        streetAddress: "4840 Wright Terr",
        locality: "Skokie",
        region: "IL",
        postalCode: "60077",
      },
      type: "REPEATING",
      ruleId: "123AAA",
      status: "COMPLETED",
      scheduledOn: "2019-09-23",
      confirmationNumber: "PBOBFZZ4",
      deliveryMethod: "TRUST_CHECK",
    },
    {
      paymentId: "876059398",
      payee: {
        id: "102260912",
        name: "Citibank Checking",
        nickName: "My Checking",
      },
      paymentMethod: {
        id: "SM1326173",
        accountName: "RETAIL PERSONAL CHECKING ",
        accountNumber: "9815",
        preferred: false,
      },
      amount: 122.05,
      deliverByDate: "2020-02-25",
      memo: "cat club dues",
      note: "notes",
      paymentAddress: {
        streetAddress: "4840 Wright Terr",
        locality: "Skokie",
        region: "IL",
        postalCode: "60077",
      },
      type: "REPEATING",
      ruleId: "123AAA",
      status: "COMPLETED",
      scheduledOn: "2019-09-23",
      confirmationNumber: "PBOBFZZ4",
      deliveryMethod: "TRUST_CHECK",
    },

    {
      paymentId: "876053212",
      payee: {
        id: "102260910",
        name: "Discover Credit Cards",
        nickName: "DiscoverCard",
        accountNumber: "************4065",
      },
      paymentMethod: {
        id: "SM1326100",
        accountName: "RETAIL PERSONAL TEST ",
        accountNumber: "9811",
        preferred: false,
      },
      amount: 1.3,
      deliverByDate: daysInFuture(0),
      note: "Have a nice day",
      type: "ONE_TIME",
      status: "SCHEDULED",
      scheduledOn: "2019-09-10",
      confirmationNumber: "ABZB2ZZ4",
      deliveryMethod: "STANDARD_ELECTRONIC",
    },
    {
      paymentId: "876059391",
      payee: {
        id: "102260912",
        name: "Citibank Checking",
        nickName: "My Checking",
      },
      paymentMethod: {
        id: "SM1326173",
        accountName: "RETAIL PERSONAL CHECKING ",
        accountNumber: "9815",
        preferred: false,
      },
      amount: 12.0,
      deliverByDate: "2020-02-28",
      memo: "this is one-time",
      note: "notes",
      paymentAddress: {
        streetAddress: "4840 Wright Terr",
        locality: "Skokie",
        region: "IL",
        postalCode: "60077",
      },
      type: "ONE_TIME",
      status: "INSUFFICIENT_FUNDS",
      scheduledOn: "2019-09-23",
      confirmationNumber: "PBOBFZZ4",
      deliveryMethod: "TRUST_CHECK",
    },

    {
      paymentId: "876053287",
      payee: {
        id: "102260910",
        name: "Discover Credit Cards",
        nickName: "DiscoverCard",
        accountNumber: "************4065",
      },
      paymentMethod: {
        id: "SM1326173",
        accountName: "RETAIL PERSONAL CHECKING ",
        accountNumber: "9815",
        preferred: false,
      },
      amount: 22.51,
      deliverByDate: "2020-09-24",
      type: "REPEATING",
      ruleId: "999SSS",
      status: "SCHEDULED",
      scheduledOn: "2019-09-09",
      confirmationNumber: "ABZB2ZZ4",
      deliveryMethod: "STANDARD_ELECTRONIC",
    },
    {
      paymentId: "876053288",
      payee: {
        id: "102260919",
        name: "Discover Credit Cards",
        nickName: "DiscoverCard",
        accountNumber: "************4065",
      },
      paymentMethod: {
        id: "SM1326173",
        accountName: "RETAIL PERSONAL CHECKING ",
        accountNumber: "9815",
        preferred: false,
      },
      amount: 22.51,
      deliverByDate: "2020-10-24",
      type: "REPEATING",
      ruleId: "999SSS",
      status: "SCHEDULED",
      scheduledOn: "2019-10-24",
      confirmationNumber: "ABZB2ZZ4",
      deliveryMethod: "STANDARD_ELECTRONIC",
    },
    {
      paymentId: "876053213",
      payee: {
        id: "102260910",
        name: "Discover Credit Cards",
        nickName: "DiscoverCard",
        accountNumber: "************4065",
      },
      paymentMethod: {
        id: "SM1326100",
        accountName: "RETAIL PERSONAL TEST ",
        accountNumber: "9811",
        preferred: false,
      },
      amount: 5.05,
      deliverByDate: "2020-09-29",
      type: "ONE_TIME",
      status: "SCHEDULED",
      scheduledOn: "2019-09-14",
      confirmationNumber: "ABZB2ZZ4",
      deliveryMethod: "STANDARD_ELECTRONIC",
    },
    {
      paymentId: "876060123",
      payee: {
        id: "102281723",
        name: "Discover Credit Card",
        nickName: "Discover CC available ebill",
      },
      paymentMethod: {
        id: "SM1326173",
        accountName: "RETAIL PERSONAL CHECKING",
        accountNumber: "9815",
        preferred: false,
      },
      amount: 1967.7,
      deliverByDate: "2020-09-25",
      note: "fun note!",
      type: "ONE_TIME",
      status: "SCHEDULED",
      scheduledOn: "2019-09-01",
      confirmationNumber: "MB2BGZZ4",
      deliveryMethod: "STANDARD_ELECTRONIC",
    },
    {
      paymentId: "876060321",
      payee: {
        id: "102260911",
        name: "Wachovia Bank",
        nickName: "Wachovia Bank active ebill",
      },
      paymentMethod: {
        id: "SM1326173",
        accountName: "RETAIL PERSONAL CHECKING",
        accountNumber: "9815",
        preferred: false,
      },
      amount: 122.05,
      deliverByDate: "2020-09-25",
      note: "howdy",
      paymentAddress: {
        streetAddress: "4840 Wright Terr",
        extendedAddress: "APT 111",
        locality: "Skokie",
        region: "IL",
        postalCode: "60077",
      },
      type: "ONE_TIME",
      status: "SCHEDULED",
      scheduledOn: "2019-09-01",
      confirmationNumber: "MB2BGZZ4",
      deliveryMethod: "STANDARD_ELECTRONIC",
    },
    {
      paymentId: "876060355",
      payee: {
        id: "102260999",
        name: "Chase Bank",
        nickName: "Chase Bank has Autopay",
        accountNumber: "************9999",
      },
      paymentMethod: {
        id: "SM1326173",
        accountName: "RETAIL PERSONAL CHECKING",
        accountNumber: "9815",
        preferred: false,
      },
      amount: 55.05,
      deliverByDate: daysInFuture(0),
      note: "this is an autopay",
      type: "EBILL_AUTOPAY",
      status: "SCHEDULED",
      scheduledOn: "2019-09-01",
      confirmationNumber: "MB2BGZZ4",
      deliveryMethod: "STANDARD_ELECTRONIC",
    },
    {
      paymentId: "102260998",
      payee: {
        id: "102260910",
        name: "Happy Bank",
        nickName: "Happy Bank Ebills Repeating Payment",
        accountNumber: "************4065",
      },
      paymentMethod: {
        id: "SM1326173",
        accountName: "RETAIL PERSONAL CHECKING ",
        accountNumber: "9815",
        preferred: false,
      },
      amount: 235.05,
      deliverByDate: "2020-10-24",
      type: "REPEATING",
      ruleId: "333ZZZ",
      status: "SCHEDULED",
      scheduledOn: "2019-10-24",
      confirmationNumber: "ABZB2ZZ4",
      deliveryMethod: "STANDARD_ELECTRONIC",
    },
    {
      paymentId: "876059300",
      payee: {
        id: "102260111",
        name: "Covid has Repeating Nothing Scheduled",
        nickName: "Covid has Repeating Nothing Scheduled",
      },
      paymentMethod: {
        id: "SM1326173",
        accountName: "RETAIL PERSONAL CHECKING ",
        accountNumber: "9815",
        preferred: false,
      },
      amount: 122.05,
      deliverByDate: "2020-02-25",
      memo: "cat club dues",
      note: "notes",
      paymentAddress: {
        streetAddress: "123 Sesame Street",
        extendedAddress: "2nd Floor",
        locality: "Indianapolis",
        region: "IN",
        postalCode: "462201234",
        formatted: "123 Sesame Street  \nIndianapolis IN 462201234\n USA",
      },
      type: "REPEATING",
      ruleId: "777888",
      status: "COMPLETED",
      scheduledOn: "2019-09-23",
      confirmationNumber: "PBOBFZZ4",
      deliveryMethod: "TRUST_CHECK",
    },
  ],
};
