module.exports = {
  default: [
    {
      paymentId: "876053212",
      payee: {
        id: "102260910",
        name: "Discover Credit Cards",
        nickName: "DiscoverCard",
        accountNumber: "********4065",
      },
      paymentMethod: {
        id: "SM1326100",
        accountName: "RETAIL PERSONAL TEST ",
        accountNumber: "9811",
        preferred: false,
      },
      amount: 1.33,
      deliverByDate: "2019-09-23",
      memo: "a repeating payment",
      note: "Have a nice day",
      type: "ONE_TIME",
      status: "SCHEDULED",
      scheduledOn: "2019-09-10",
      confirmationNumber: "ABZB2ZZ4",
      deliveryMethod: "STANDARD_ELECTRONIC",
    },
    {
      paymentId: "876053287",
      payee: {
        id: "102260910",
        name: "Discover Credit Cards",
        nickName: "DiscoverCard",
        accountNumber: "********4065",
      },
      paymentMethod: {
        id: "SM1326173",
        accountName: "RETAIL PERSONAL CHECKING",
        accountNumber: "********9815",
        preferred: false,
      },
      amount: 22.51,
      deliverByDate: "2019-09-24",
      memo: "a repeating payment",
      type: "REPEATING",
      ruleId: "999SSS",
      status: "SCHEDULED",
      scheduledOn: "2019-09-09",
      confirmationNumber: "ABZB2ZZ4",
      deliveryMethod: "STANDARD_ELECTRONIC",
    },
    {
      paymentId: "876060900",
      payee: {
        id: "102260911",
        name: "Wachovia Bank",
        nickName: "Wachovia Bank",
      },
      paymentMethod: {
        id: "SM1326173",
        accountName: "RETAIL PERSONAL CHECKING",
        accountNumber: "********9815",
        preferred: false,
      },
      amount: 122.05,
      deliverByDate: "2019-9-25",
      memo: "this is a managed payee",
      paymentAddress: {
        streetAddress: "4840 Wright Terr",
        locality: "Skokie",
        region: "IL",
        postalCode: "60077",
      },
      type: "REPEATING",
      ruleId: "123AAA",
      status: "SCHEDULED",
      scheduledOn: "2019-09-01",
      confirmationNumber: "MB2BGZZ4",
      deliveryMethod: "TRUST_CHECK",
    },
    {
      paymentId: "876053213",
      payee: {
        id: "102260912",
        name: "Citibank Checking",
        nickName: "My Checking",
        accountNumber: "*******2374",
      },
      paymentMethod: {
        id: "SM1326100",
        accountName: "RETAIL PERSONAL TEST",
        accountNumber: "9811",
        preferred: false,
      },
      amount: 5.05,
      deliverByDate: "2019-09-26",
      memo: "a repeating payment",
      type: "ONE_TIME",
      status: "SCHEDULED",
      scheduledOn: "2019-09-14",
      confirmationNumber: "ABZB2ZZ4",
      deliveryMethod: "STANDARD_ELECTRONIC",
    },
  ],
};
